---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    repo: jonnrb/wifi_dash
    username:
      from_secret: docker_username

...
